<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FeedCSVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedCSVRepository extends EntityRepository
{
    public function retrieveNextCsvFeed($source, $locale)
    {
        $query = $this->_em->createQuery(
            "
                SELECT
                  s
                FROM AppBundle\Entity\FeedCSV s
                WHERE s.source = :source
                AND s.flagbatched = 'N'
                AND s.active = 'Y'
                AND s.locale = :locale
            "
        );

        $query->setParameter('locale', $locale);
        $query->setParameter('source', strtoupper($source));
        $query->setMaxResults(1);
        $query->setFirstResult(0);
        $results = $query->getResult();

        return $results[0];
    }

    public function getFeedsToProcess($source, $locale){

        $feedsToProcess = $this->findBy(
            array(
                'locale' => $locale,
                'source' => $source,
                'flagbatched' => 'N',
                'active' => 'Y'
            )
        );

        return $feedsToProcess;
    }

    public function getActiveFeeds($source, $locale){

        $feedsToProcess = $this->findBy(
            array(
                'locale' => $locale,
                'source' => $source,
                'active' => 'Y'
            )
        );
        return $feedsToProcess;
    }



    
}
