<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Cocur\Slugify\Slugify;
use AppBundle\Utils\Sources;


/**
 * PendingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PendingRepository extends EntityRepository
{

    public function getPaginatedCategoriesToValidate($page, $maxArticles, $locale)
    {
        $query = $this->_em->createQuery(
            "
                SELECT
                  p
                FROM AppBundle\Entity\Pending p
            "
        );

        return $query->getResult();

    }

    public function createOrReplacePending($params, $source)
    {
        $slugify = new Slugify();
        $source_category = Sources::getSourceKey($source, 'merchantCategoryName');

        $slugified_source_category = $slugify->slugify($params['produit'][$source_category] );
        $label = $params['produit'][$source_category] ;


        $statement = $this->_em->getConnection()->prepare('
                                INSERT INTO pending
                                SET
                                    id        = :slugified_source_category ,
                                    label     = :label ,
                                    createdAt =  NOW()
                                ON DUPLICATE KEY UPDATE
                                    createdAt  =  NOW() ');

        $statement->bindValue('slugified_source_category', $slugified_source_category);
        $statement->bindValue('label', $label);


        $statement->execute();
    }
}
