app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#REST
rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api
