#src/Obtao/UserBundle/Resources/config/routing_rest.yml
users :
  type: rest
  resource:     "AppBundle:UserRest"
  name_prefix:  api_
feed :
  type: rest
  resource:     "AppBundle:FeedCSVRest"
  name_prefix:  api_
products :
  type: rest
  resource:     "AppBundle:ProductsRest"
  name_prefix:  api_