#src/Obtao/UserBundle/Resources/config/routing_rest.yml
users :
  type: rest
  resource:     "AppBundle:UserRest"
  name_prefix:  api_
feed :
  type: rest
  resource:     "AppBundle:FeedCSVRest"
  name_prefix:  api_
products :
  type: rest
  resource:     "AppBundle:ProductsRest"
  name_prefix:  api_
categories :
  type: rest
  resource:     "AppBundle:CategoriesRest"
  name_prefix:  api_
pending :
  type: rest
  resource:     "AppBundle:PendingRest"
  name_prefix:  api_
whitelist_categories :
  type: rest
  resource:     "AppBundle:WhiteListCategoriesRest"
  name_prefix:  api_
blacklist_categories :
  type: rest
  resource:     "AppBundle:BlackListCategoriesRest"
  name_prefix:  api_